### ISSUE TITLE
big buttons

### ISSUE THREAD

**Issue by Efimero** [kreezxil/More-Beautiful-Buttons#1]
what if you had big buttons?
like the old openblocks big button
but with every texture =D

**Comment by kreezxil** [comment]
The same buttons but fatter? Can you send me a link or picture?

**Comment by kreezxil** [comment]
I found it! I'll have a new mod out for you that does this during the next 24 hours.

**Comment by kreezxil** [comment]
https://github.com/kreezxil/big-beautiful-buttons

**Comment by kreezxil** [comment]
Got a mod for you:
https://github.com/kreezxil/big-beautiful-buttons

https://minecraft.curseforge.com/projects/big-beautiful-buttons

Closes #1

**Comment by Efimero** [comment]
perfect <3 <3 <3
